/** @file
    @brief The main header file for the CORA library.

    This file provides the primary interface to the CORA library. All
    usage of the library should be done through this file.
*/

#pragma once

#include <CORA/CORA_problem.h>
#include <CORA/CORA_types.h>
#include <CORA/pyfg_text_parser.h>
#include <string>
#include <utility>
#include <vector>

namespace CORA {

using CoraTntResult = Optimization::Riemannian::TNTResult<Matrix, Scalar>;
//using CoraResult = std::pair<CoraTntResult, std::vector<Matrix>>;



// Put all the SE-Sync's result here firstly
struct CoraResult{

  /** An estimate of a global minimizer Yopt of the rank-restricted dual
   * semidefinite relaxation Problem 9 in the SE-Sync tech report.  The
   * corresponding solution of Problem 7 is Z = Y^T Y */
  Matrix Yopt;

  /** The value of the objective F(Y^T Y) = F(Z) attained by the Yopt */
  Scalar SDPval;
  std::vector<Scalar> SDPvalVector;

  /** The norm of the Riemannian gradient at Yopt */
  Scalar gradnorm;
  std::vector<Scalar> gradnormVector;

  /** The Lagrange multiplier matrix Lambda corresponding to Yopt, computed
   * according to eq. (119) in the SE-Sync tech report.  If Z = Y^T Y is an
   * exact solution for the dual semidefinite relaxation Problem 7, then Lambda
   * is the solution to the primal Lagrangian relaxation Problem 6. */
  SparseMatrix Lambda;

  /** The trace of Lambda; this is the value of Lambda under the objective of
   * the (primal) semidefinite relaxation Problem 6. */
  Scalar trLambda;

  /** The duality gap between the estimates for the primal and dual solutions
   * Lambda and Z = Y^T Y of Problems 7 and 6, respectively; it is given by:
   *
   * duality_gap := F(Y^T Y) - tr(Lambda)
   *
   */
  Scalar duality_gap;

  /** The objective value of the rounded solution xhat in SE(d)^n */
  Scalar Fxhat;

  /** The rounded solution xhat = [t | R] in SE(d)^n */
  Matrix xhat;

  /** Upper bound on the global suboptimality of the recovered estimates
   * xhat; this is equal to F(xhat) - tr(Lambda) */
  Scalar suboptimality_bound;

  /** The total elapsed computation time for the SE-Sync algorithm */
  double total_computation_time;

  /** The elapsed computation time used to compute the initialization for the
   * Riemannian Staircase */
  double initialization_time;

  /** A vector containing the sequence of function values obtained during the
   * optimization at each level of the Riemannian Staircase */
  std::vector<std::vector<Scalar>> function_values;

  /** A vector containing the sequence of norms of the Riemannian gradients
   * obtained during the optimization at each level of the Riemannian Staircase
   */
  std::vector<std::vector<Scalar>> gradient_norms;

  /** A vector containing the sequence of norms of the preconditioned Riemannian
   * gradients obtained during the optimization at each level of the Riemannian
   * Staircase */
  std::vector<std::vector<Scalar>> preconditioned_gradient_norms;

  /** A vector containing the sequence of (# Hessian-vector product operations)
   * carried out during the optimization at each level of the Riemannian
   * Staircase */
  std::vector<std::vector<size_t>> Hessian_vector_products;

  /** A vector containing the sequence of norms of the update steps computed
   * during the optimization at each level of the Riemannian Staircase */
  std::vector<std::vector<Scalar>> update_step_norms;

  /** A vector containing the sequence of M-norms | h_k |_{M_k} of the update
   * steps h_k computed during the optimization at each level of the Riemannian
   * Staircase, where M_k is the preconditioner constructed in the kth iteration
   */
  std::vector<std::vector<Scalar>> update_step_M_norms;

  /** A vector containing the sequence of gain ratios for the update steps
   * computed during optimization at each level of the Riemannian Staircase */
  std::vector<std::vector<Scalar>> gain_ratios;

  /** A vector containing the sequence of elapsed times in the optimization at
   * each level of the Riemannian Staircase at which the corresponding function
   * values and gradients were obtained */
  std::vector<std::vector<double>> elapsed_optimization_times;

  /** A vector containing the sequence of curvatures theta := x'*S*x of the
   * certificate matrices S along the computed escape directions x from
   * suboptimal critical points at each level of the Riemannian Staircase
   */
  std::vector<Scalar> escape_direction_curvatures;

  /** A vector containing the number of LOBPCG iterations performed for the
   * minimum-eigenpair computation at each level of the Riemannian Staircase */
  std::vector<size_t> LOBPCG_iters;

  /** A vector containing the elapsed time needed to perform solution
   * verification at each level of the Riemannian Staircase */
  std::vector<double> verification_times;

  /** If log_iterates = true, this will contain the sequence of iterates
   * generated by the truncated-Newton trust-region method at each
   * level of the Riemannian Staircase */
  std::vector<std::vector<Matrix>> iterates;

  // Riemannian staricase level used, i.e, all the rank we used
  std::vector<size_t> rank_iters;

  // Final Solution refinement time
  double final_refinement_time;
};


CoraResult solveCORA(Problem &problem, const Matrix &x0,
                     int max_relaxation_rank = 20, bool verbose = false,
                     bool log_iterates = false, bool show_iterates = false,
                     std::optional<Optimization::Riemannian::TNTParams<Scalar>>
                         params = std::nullopt);
inline CoraResult solveCORA(std::string filepath) {
  Problem problem = parsePyfgTextToProblem(filepath);
  Matrix x0 = Matrix();
  throw std::runtime_error(
      "Not implemented -- need to decide how to get initialization");
  return solveCORA(problem, x0);
}

Matrix saddleEscape(const Problem &problem, const Matrix &Y, Scalar theta,
                    const Vector &v, Scalar gradient_tolerance,
                    Scalar preconditioned_gradient_tolerance);

Matrix projectSolution(const Problem &problem, const Matrix &Y,
                       bool verbose = false);

} // namespace CORA
